# Generated by Django 4.0.6 on 2022-08-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('articulo', models.IntegerField()),
                ('stock', models.BooleanField()),
            ],
        ),
    ]
