# Generated by Django 4.0.6 on 2022-09-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVistas', '0002_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
            ],
        ),
    ]
