# Generated by Django 4.0.6 on 2022-09-02 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppVistas', '0003_marcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='actividad',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
