# Generated by Django 4.0.6 on 2022-09-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVistas', '0004_marcas_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='actividad',
            new_name='Inicio_Actividad',
        ),
    ]
