# Generated by Django 4.0.6 on 2022-09-05 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppVistas', '0006_producto_fecha_producto_hora_producto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
