# Generated by Django 4.0.6 on 2022-09-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVistas', '0007_proveedores_fecha_proveedores_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='usuario',
        ),
    ]
