# Generated by Django 4.0.6 on 2022-09-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVistas', '0008_remove_proveedores_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='hora',
        ),
    ]
