# Generated by Django 4.0.6 on 2022-09-03 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=400)),
                ('fecha', models.DateField(verbose_name=datetime.datetime(2022, 9, 3, 0, 7, 53, 517896))),
            ],
        ),
    ]
