# Generated by Django 4.0.6 on 2022-09-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppForo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='fecha',
        ),
    ]
