# Generated by Django 4.0.6 on 2022-09-03 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppForo', '0002_remove_foro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
