# Generated by Django 4.0.6 on 2022-09-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppForo', '0004_foro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
