# Generated by Django 4.0.6 on 2022-09-03 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppForo', '0005_alter_foro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foro',
            name='fecha',
            field=models.DateField(),
        ),
    ]
