# Generated by Django 4.0.6 on 2022-09-03 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppForo', '0007_remove_foro_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
